<?php
// This script and data application were generated by AppGini 5.81
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/Details.php");
	include("$currDir/Details_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('Details');
	if(!$perm[0]) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "Details";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(
		"`Details`.`ID`" => "ID",
		"`Details`.`Due_Date`" => "Due_Date",
		"`Details`.`Domain`" => "Domain",
		"`Details`.`Sub_Domains`" => "Sub_Domains",
		"`Details`.`Crazy_Domains`" => "Crazy_Domains",
		"`Details`.`DNS_Provider`" => "DNS_Provider",
		"CONCAT('$', FORMAT(`Details`.`Yearly_Fee`, 2))" => "Yearly_Fee",
		"`Details`.`Company_Name`" => "Company_Name",
		"`Details`.`Contact`" => "Contact",
		"`Details`.`Email_Address`" => "Email_Address",
		"`Details`.`Alternative_Email`" => "Alternative_Email",
		"`Details`.`Notes`" => "Notes",
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(
		1 => '`Details`.`ID`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => '`Details`.`Yearly_Fee`',
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(
		"`Details`.`ID`" => "ID",
		"`Details`.`Due_Date`" => "Due_Date",
		"`Details`.`Domain`" => "Domain",
		"`Details`.`Sub_Domains`" => "Sub_Domains",
		"`Details`.`Crazy_Domains`" => "Crazy_Domains",
		"`Details`.`DNS_Provider`" => "DNS_Provider",
		"CONCAT('$', FORMAT(`Details`.`Yearly_Fee`, 2))" => "Yearly_Fee",
		"`Details`.`Company_Name`" => "Company_Name",
		"`Details`.`Contact`" => "Contact",
		"`Details`.`Email_Address`" => "Email_Address",
		"`Details`.`Alternative_Email`" => "Alternative_Email",
		"`Details`.`Notes`" => "Notes",
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(
		"`Details`.`ID`" => "ID",
		"`Details`.`Due_Date`" => "Month Due",
		"`Details`.`Domain`" => "Main Domain",
		"`Details`.`Sub_Domains`" => "Sub Domains",
		"`Details`.`Crazy_Domains`" => "Domain Registrar",
		"`Details`.`DNS_Provider`" => "DNS Provider",
		"`Details`.`Yearly_Fee`" => "Yearly Fee",
		"`Details`.`Company_Name`" => "Company Name",
		"`Details`.`Contact`" => "Contact",
		"`Details`.`Email_Address`" => "Email Address",
		"`Details`.`Alternative_Email`" => "Alternative Email",
		"`Details`.`Notes`" => "Notes",
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(
		"`Details`.`ID`" => "ID",
		"`Details`.`Due_Date`" => "Due_Date",
		"`Details`.`Domain`" => "Domain",
		"`Details`.`Sub_Domains`" => "Sub_Domains",
		"`Details`.`Crazy_Domains`" => "Crazy_Domains",
		"`Details`.`DNS_Provider`" => "DNS_Provider",
		"CONCAT('$', FORMAT(`Details`.`Yearly_Fee`, 2))" => "Yearly_Fee",
		"`Details`.`Company_Name`" => "Company_Name",
		"`Details`.`Contact`" => "Contact",
		"`Details`.`Email_Address`" => "Email_Address",
		"`Details`.`Alternative_Email`" => "Alternative_Email",
		"`Details`.`Notes`" => "Notes",
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`Details` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "Details_view.php";
	$x->RedirectAfterInsert = "Details_view.php?SelectedID=#ID#";
	$x->TableTitle = "oz4host Domains";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`Details`.`ID`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 80, 150, 150, 150);
	$x->ColCaption = array("Month Due", "Main Domain", "Sub Domains", "Domain Registrar", "DNS Provider", "Yearly Fee", "Company Name", "Contact", "Email Address");
	$x->ColFieldName = array('Due_Date', 'Domain', 'Sub_Domains', 'Crazy_Domains', 'DNS_Provider', 'Yearly_Fee', 'Company_Name', 'Contact', 'Email_Address');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10);

	// template paths below are based on the app main directory
	$x->Template = 'templates/Details_templateTV.html';
	$x->SelectedTemplate = 'templates/Details_templateTVS.html';
	$x->TemplateDV = 'templates/Details_templateDV.html';
	$x->TemplateDVP = 'templates/Details_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';
	$x->HasCalculatedFields = false;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))) { $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Details`.`ID`=membership_userrecords.pkValue and membership_userrecords.tableName='Details' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Details`.`ID`=membership_userrecords.pkValue and membership_userrecords.tableName='Details' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3) { // view all
		// no further action
	}elseif($perm[2]==0) { // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`Details`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: Details_init
	$render=TRUE;
	if(function_exists('Details_init')) {
		$args=array();
		$render=Details_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Details_header
	$headerCode='';
	if(function_exists('Details_header')) {
		$args=array();
		$headerCode=Details_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode) {
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: Details_footer
	$footerCode='';
	if(function_exists('Details_footer')) {
		$args=array();
		$footerCode=Details_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode) {
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>